version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-shopUsa-container
    environment:
      POSTGRES_DB: shopUsaDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
